# docker-compose.yml

version: '3'

services:
  django-app:
    restart: always
    ports:
      - "8000:8000"
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
